version: 0.1

phases:
  install:
    commands:
      - pip install -U -r requirements.txt
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - tox -e py35
  post_build:
    commands:
      - echo Build completed on `date`
